//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_master
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public string divs { get; set; }
        public string roles { get; set; }
        public byte[] lastchanged { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_by { get; set; }
    }
}
